---
# template-gh-lint: 1.2.0
name: "Lint / ShellCheck"

env:
  DEV_CICD_DEBUG: ""
  BL64_LIB_CICD: "YES"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"

jobs:
  lint-shellcheck:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache local tools"
        uses: "actions/cache@v4"
        with:
          path: ./lib
          key: ${{ runner.os }}-lib-cache
          restore-keys: |
            ${{ runner.os }}-lib-cache

      - name: "Prepare environment"
        run: "./bin/dev-lib-base"

      - name: "Run tests"
        run: "./bin/dev-lint-shellcheck"
...
