---
# Template: 2.3.0
name: "Test / Bash"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ""
  BL64_LIB_CICD: "YES"
  DEV_TEST_BASH_RUNNER_ENVIRONMENT: "ON"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"
      - "test/bash/**"

jobs:
  test-bash:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache local tools"
        uses: "actions/cache@v4"
        with:
          path: ./lib
          key: ${{ runner.os }}-lib-cache
          restore-keys: |
            ${{ runner.os }}-lib-cache

      - name: "Prepare environment"
        run: |
          ./bin/dev-lib-base &&
          ./bin/dev-prep-project &&
          ./bin/dev-lib-project

      - name: "Run tests"
        run: "./bin/dev-test-bash"
...
